### ISSUE TITLE
torizoncore-builder ignore package-version on platform push for images

### ISSUE THREAD

**Issue by lzaugg** [torizon/torizoncore-builder#4]
Hi,

When executing `torizoncore-builder platform push --credentials credentials.zip --package-name some-name --package-version 0.2.0 tcbuilder-20230320111710` the image for `colibri-imx8x` gets updated, but with the default version identifier `TorizonCore Builder union commit created at 2023-03-20T11:17:11 ` instead of the `0.2.0` given as argument.

For me it looks like a bug 🤷 . Or do I miss something?

Additional info:
- When pushing docker-compose files, the `platform-version` attribute is taken into account without issues.
- Using torizoncore-builder image version `3.7.0`

**Comment by microhobby** [comment]
Hi @lzaugg ,

in the `3.7.0` we are now setting the `version` property metadata instead of using the `ostree` `commitSubject` as version, and this was not updated in the [torizon.io](https://www.torizon.io/) platform UI yet.

But now if you refresh the page, this should be fixed and should show the version that you set by the `--package-version`.

Let me know if this is working for you.

**Comment by lzaugg** [comment]
Hi @microhobby ,

Thanks for the quick fix, appreciated.

Working for me.
